server:
  port: 8091

spring.application.name: api-gateway



# add more paths, filters, predicates later.
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

eureka:
  instance.prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/

# okta:
#   oauth2:
#     client-id: 0oae558kdiXkZM1KI5d7
#     client-secret: KMynKhgxCkMUCpduORW5KYOwhUyrn0gRsZTBhEhsYjgqlwLn4BJe7jGVBgrhCqe9
#     issuer: https://dev-69493338.okta.com/oauth2/default
#     audience: api://default
#     scopes: openid, email, profile, offline_access
